/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      colors: {
        background: "#faf9fc",
        surface: "#faf9fc",
        "surface-bright": "#faf9fc",
        "surface-dim": "#dbd9dd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f7",
        "surface-container": "#efedf1",
        "surface-container-high": "#e9e7eb",
        "surface-container-highest": "#e3e2e6",
        "surface-variant": "#e3e2e6",
        "on-background": "#1b1b1e",
        "on-surface": "#1b1b1e",
        "on-surface-variant": "#44474e",
        outline: "#74777f",
        "outline-variant": "#c4c6cf",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#001a3f",
        "on-primary-container": "#6f84ae",
        "primary-fixed": "#d7e2ff",
        "primary-fixed-dim": "#b2c7f5",
        "on-primary-fixed": "#001a3f",
        secondary: "#7d5700",
        "on-secondary": "#ffffff",
        "secondary-container": "#feb721",
        "on-secondary-container": "#6c4a00",
        "secondary-fixed": "#ffdeab",
        "tertiary-container": "#001a41",
        "on-tertiary-fixed-variant": "#004493",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
      },
      spacing: {
        "container-padding": "16px",
        "stack-gap": "12px",
        "section-margin": "24px",
        gutter: "12px",
      },
      boxShadow: {
        soft: "0 2px 10px rgba(0,0,0,0.04)",
        header: "0 8px 30px rgba(0,0,0,0.12)",
      },
    },
  },
  plugins: [],
};
