export const adminSeedData = {
  places: [],
  users: [
    {
      id: "usr-001",
      firstName: "Олександр",
      lastName: "Шевченко",
      username: "alex",
      email: "alex.shevchenko@email.com",
      phone: "+380 50 123 4567",
      role: "user",
      status: "active",
      address: "вул. Театральна, 15",
      createdAt: "2026-05-10",
    },
    {
      id: "usr-002",
      firstName: "Ірина",
      lastName: "Ковальчук",
      username: "iryna.admin",
      email: "admin@zhytomate.local",
      phone: "+380 67 212 8841",
      role: "admin",
      status: "active",
      address: "майдан Соборний, 4",
      createdAt: "2026-04-28",
    },
    {
      id: "usr-003",
      firstName: "Марко",
      lastName: "Литвин",
      username: "marko",
      email: "marko.lytvyn@email.com",
      phone: "+380 93 440 1902",
      role: "user",
      status: "blocked",
      address: "вул. Київська, 102",
      createdAt: "2026-06-02",
    },
  ],
  surveys: [
    {
      id: "srv-001",
      title: "Оновлення скверу на Михайлівській",
      description: "Місто збирає думки мешканців щодо сценарію реконструкції центрального скверу.",
      category: "Інфраструктура",
      status: "active",
      startsAt: "2026-07-01",
      endsAt: "2026-07-21",
      totalVotes: 1842,
      options: [
        { id: "o1", label: "Більше зелених зон", votes: 921, percent: 50 },
        { id: "o2", label: "Дитячий майданчик", votes: 553, percent: 30 },
        { id: "o3", label: "Сцена для подій", votes: 368, percent: 20 },
      ],
    },
    {
      id: "srv-002",
      title: "Нічний громадський транспорт",
      description: "Пілотні маршрути у вихідні між центром, вокзалом і мікрорайонами.",
      category: "Транспорт",
      status: "draft",
      startsAt: "2026-07-15",
      endsAt: "2026-08-01",
      totalVotes: 0,
      options: [
        { id: "o1", label: "Запустити пілот", votes: 0, percent: 0 },
        { id: "o2", label: "Доопрацювати маршрут", votes: 0, percent: 0 },
      ],
    },
  ],
  announcements: [
    {
      id: "ann-001",
      title: "Планове відключення води",
      body: "12 липня з 09:00 до 17:00 буде тимчасово припинено водопостачання на кількох вулицях Богунського району.",
      audience: "Богунський район",
      priority: "high",
      status: "published",
      publishAt: "2026-07-10 08:00",
      author: "КП Житомирводоканал",
    },
    {
      id: "ann-002",
      title: "Перекриття руху біля парку",
      body: "На час проведення міського забігу рух транспорту біля Шодуарівського парку буде обмежено.",
      audience: "Усі мешканці",
      priority: "medium",
      status: "draft",
      publishAt: "2026-07-18 07:30",
      author: "Управління транспорту",
    },
  ],
  news: [
    {
      id: "news-001",
      title: "У Житомирі відкрили оновлений простір для молоді",
      body: "Новий простір працюватиме як місце для навчання, подій і консультацій для молодіжних ініціатив.",
      source: "Житомирська міська рада",
      category: "Події",
      status: "published",
      date: "2026-07-05",
      tags: "#молодь #події",
    },
    {
      id: "news-002",
      title: "Комунальні служби оновили графік прибирання",
      body: "Місто переходить на оновлений графік прибирання дворів і зупинок громадського транспорту.",
      source: "Департамент благоустрою",
      category: "Комуналка",
      status: "review",
      date: "2026-07-06",
      tags: "#благоустрій #комуналка",
    },
  ],
  appeals: [
    {
      id: "apl-001",
      user: "Олександр Шевченко",
      userId: "usr-001",
      category: "Яма",
      address: "просп. Перемоги, 55",
      description: "Глибока вибоїна на правій смузі руху створює аварійну ситуацію.",
      status: "in_progress",
      imageUrl: "",
      createdAt: "2026-07-04",
    },
    {
      id: "apl-002",
      user: "Марко Литвин",
      userId: "usr-003",
      category: "Освітлення",
      address: "вул. Київська, 102",
      description: "Не працює ліхтар біля дитячого майданчика у дворі.",
      status: "new",
      imageUrl: "",
      createdAt: "2026-07-06",
    },
  ],
};
